# Generated by Django 3.0.6 on 2020-05-28 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_endpoint', models.CharField(max_length=100)),
                ('api_sample_url', models.CharField(max_length=100)),
                ('api_port', models.IntegerField()),
                ('api_method', models.CharField(max_length=10)),
                ('api_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMst',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgMst',
            fields=[
                ('org_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_type', models.CharField(max_length=100)),
                ('admin', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiSamples',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('status', models.IntegerField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docs.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ApiParams',
            fields=[
                ('param_id', models.IntegerField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=100)),
                ('param_type', models.CharField(max_length=100)),
                ('param_required', models.BooleanField()),
                ('param_sample', models.CharField(max_length=100)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docs.Api')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docs.ProjectMst'),
        ),
    ]
