# Generated by Django 3.0.6 on 2020-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmst',
            name='project_base_port',
            field=models.IntegerField(blank=True, default=8000, null=True),
        ),
        migrations.AddField(
            model_name='projectmst',
            name='project_base_url',
            field=models.CharField(default='localhost', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmst',
            name='project_description',
            field=models.TextField(default='just a test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiparams',
            name='param_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apisamples',
            name='sample_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orgmst',
            name='org_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectmst',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
