# Generated by Django 3.0.6 on 2020-05-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200529_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
    ]
