# Generated by Django 3.0.6 on 2020-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
